#!/usr/bin/env bash

# if there is a CHPL_HOME, use that to find mason
# if that fails, fall back to the mason in path

mason="none"

if [ -n "$CHPL_HOME" ]; then
  chpl_python=$($CHPL_HOME/util/config/find-python.sh 2> /dev/null)
  exit_code=$?
  if [ $exit_code -eq 0 ]; then
    chpl_bin_subdir=$($chpl_python $CHPL_HOME/util/chplenv/chpl_bin_subdir.py)
    mason="$CHPL_HOME/bin/$chpl_bin_subdir/mason"
  fi
else
  mason="$(command -v mason)"
fi

if [ ! -x "$mason" ]; then
  echo "Could not find suitable install of 'mason' in \$CHPL_HOME or \$PATH"
  exit 1
fi

if [ -z "$CHPL_HOME" ]; then
  unset CHPL_HOME
fi

$mason "$@"
