name: Bump version

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Upload VSCode packages]
    types: [completed]

jobs:
  bump-patch:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: lts/*
    - name: Exit if branch exists
      run: |
        BRANCH_NAME="update-version"
        if git ls-remote --heads origin $BRANCH_NAME | grep -q $BRANCH_NAME; then
          echo "Branch $BRANCH_NAME already exists."
          exit 1
        fi
    - name: Create a new branch
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b update-version
        git push --set-upstream origin update-version
    - name: Bump Version
      run: |
        npm version patch
        git push
    - name: create pull request
      run: >
        gh pr create
        -B main
        -H update-version
        --title 'Bump version for next release'
        --body 'Bump the version in prep for next release'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
