name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24, 26, lts/*, latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: |
        npm ci
        npm list -a
    - name: Test
      run: |
        npm run pretest
        npm run test
    - name: Test packaging
      run: |
        mkdir -p bin
        npx vsce package -o bin/chapel.vsix
    - name: set artifact name
      run: |
        ARTIFACT_VER=$(sed "s/lts\/\*/lts-latest/g" <<< "${{ matrix.node-version }}")
        echo "PACKAGE_ARTIFACT_NAME=chapel-package-node${ARTIFACT_VER}.vsix" >> "$GITHUB_ENV"
    - name: upload package
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.PACKAGE_ARTIFACT_NAME }}
        path: bin/chapel.vsix
